"""Letterplace encoder for noncommutative algebras (task LP-0a).

Implements the *letterplace correspondence* (Cohen 1987; La Scala,
arXiv:1605.06944) which compiles a noncommutative algebra problem
(presentation + relations) into a commutative algebra problem in the
polynomial ring ``K[x_{i,s}]`` where ``i`` ranges over the NC
generators and ``s`` ranges over *positions* ``0 .. max_degree``.

The correspondence
------------------

A noncommutative word

    w = x_{i_1} x_{i_2} ... x_{i_d}

is encoded as the commutative monomial

    encode(w, s) = x_{i_1, s} * x_{i_2, s+1} * ... * x_{i_d, s+d-1}

where ``s`` is the *starting position*.  A noncommutative polynomial
``P = sum_j c_j w_j`` is encoded (at start ``s``) as

    P_lp(s) = sum_j c_j * encode(w_j, s).

A noncommutative relation ``LHS = RHS`` becomes the commutative
polynomial ``encode(LHS, s) - encode(RHS, s)`` for each start ``s``.
The *letterplace ideal* ``I_lp`` is generated by all such encoded
relations for all starts ``s = 0 .. max_degree - max_LHS_len``.

**Key theorem (La Scala–Levandovskyy)**: the NC free resolution of the
trivial module ``k`` over ``A = K<gens> / <relations>`` is isomorphic
(as a graded complex, up to the degree bound ``max_degree``) to the
commutative free resolution of ``k`` over the letterplace algebra
``K[x_{i,s}] / I_lp``.  This lets us compute syzygies and Ext groups
for NC algebras using the well-understood commutative Gröbner basis
machinery (e.g. :func:`sympy.groebner`).

Coefficients
------------

The NC side uses :class:`ir.parser.QLaurent` (elements of
``Z[q, q^{-1}]``) for coefficients.  These are converted to sympy
expressions in a single symbolic :class:`sympy.Symbol` ``q`` for the
commutative Gröbner computation.  For roots of unity one can either

  * substitute a concrete algebraic number (e.g. ``q = exp(2*pi*i/3)``
    for ``ell = 3``), or
  * keep ``q`` symbolic and add the minimal polynomial (e.g.
    ``q^2 + q + 1 = 0``) as an extra letterplace generator, or
  * use the specialized :class:`ir.qomega.QOmega3` coefficient ring
    (which represents ``q`` as ``omega`` with ``omega^2 + omega + 1
    = 0``) and convert to a sympy ``alpha`` algebraic element.

The encoder is generic and works with any of these strategies; the
default is the symbolic-``q`` approach, which is what the test suite
uses.
"""
from __future__ import annotations

from typing import Optional, Union

import sympy as sp

from .parser import (
    Monomial,
    Polynomial,
    QLaurent,
    RewriteRule,
    Term,
)


# ============================================================================
# LetterplaceEncoder
# ============================================================================


class LetterplaceEncoder:
    """Compile NC algebra problems into commutative ones via the letterplace correspondence.

    Parameters
    ----------
    generators : list of str
        Names of the NC generators (must match the :class:`Presentation`).
    max_degree : int
        Maximum position index ``s`` for which commutative variables
        ``x_{i,s}`` are created.  Must be ``>= 0``.  The letterplace
        ideal is correct (matches the NC resolution) only up to total
        NC degree ``max_degree``; larger ``max_degree`` gives more
        accurate resolutions at the cost of more variables.
    q_sym : sympy.Symbol, optional
        The symbolic ``q`` used when converting :class:`QLaurent`
        coefficients to sympy.  Defaults to ``sympy.Symbol('q')``.
        Callers may pass a different symbol (e.g. a root of unity) or
        an algebraic element.
    """

    def __init__(
        self,
        generators: list,
        max_degree: int,
        q_sym: Optional[sp.Symbol] = None,
        q_value: Optional[sp.Expr] = None,
    ) -> None:
        if max_degree < 0:
            raise ValueError(
                f"LetterplaceEncoder: max_degree must be >= 0, got {max_degree}"
            )
        self.generators: list = list(generators)
        self.max_degree: int = int(max_degree)
        self.n_gens: int = len(self.generators)
        self.q_sym: sp.Symbol = q_sym if q_sym is not None else sp.Symbol("q")
        # If q_value is set, all QLaurent / QOmega3 coefficients are converted
        # to sympy expressions in which ``q`` has been replaced by ``q_value``
        # (e.g. an algebraic number such as ``omega = exp(2*pi*i/3)``).  This
        # lets us compute Groebner bases over the algebraic field Q(omega)
        # rather than over the rational function field Q(q).
        self.q_value: Optional[sp.Expr] = q_value

        # Variable grid: self._vars[i][s] = sympy.Symbol(f"x{i}_s{s}").
        # Variables are created with default assumptions (commutative=True),
        # which is what we need for the letterplace ring K[x_{i,s}].
        self._vars: list = []
        for i in range(self.n_gens):
            row = [sp.Symbol(f"x{i}_s{s}") for s in range(self.max_degree + 1)]
            self._vars.append(row)

        # Flat list of all x-variables, ordered by (i, s) — i-major, s-minor.
        # This order is used as the generator list for sp.groebner.
        self._all_vars: list = [
            self._vars[i][s]
            for i in range(self.n_gens)
            for s in range(self.max_degree + 1)
        ]

        # Reverse lookup: variable name -> (generator_index, position).
        self._name_to_idx_pos: dict = {
            v.name: (i, s)
            for i, row in enumerate(self._vars)
            for s, v in enumerate(row)
        }

    # ------------------------------------------------------------------
    # Variable access
    # ------------------------------------------------------------------

    def var(self, i: int, s: int) -> sp.Symbol:
        """Return the commutative variable ``x_{i, s}``.

        Raises :class:`IndexError` if ``i`` or ``s`` is out of range.
        """
        if not (0 <= i < self.n_gens):
            raise IndexError(
                f"LetterplaceEncoder.var: generator index {i} out of "
                f"range [0, {self.n_gens})"
            )
        if not (0 <= s <= self.max_degree):
            raise IndexError(
                f"LetterplaceEncoder.var: position {s} out of range "
                f"[0, {self.max_degree}]"
            )
        return self._vars[i][s]

    def all_variables(self) -> list:
        """Return the flat list of all letterplace variables ``x_{i,s}``.

        The list is ordered by ``(i, s)`` (i-major, s-minor) and is
        suitable as the generator argument to :func:`sympy.groebner`.
        The symbolic ``q`` is *not* included (it is treated as a
        coefficient); use :meth:`coefficient_variables` to get the
        full list including ``q``.
        """
        return list(self._all_vars)

    def coefficient_variables(self) -> list:
        """Return ``[q_sym]`` — the variables that may appear in coefficients."""
        return [self.q_sym]

    def full_variable_list(self) -> list:
        """Return ``[x-vars..., q_sym]`` — all variables for a Groebner call.

        The symbolic ``q`` is placed *last* so that with ``lex`` order
        the leading terms are determined by the x-variables (which is
        the letterplace-friendly orientation: NC LHS monomials become
        leading terms).
        """
        return list(self._all_vars) + [self.q_sym]

    # ------------------------------------------------------------------
    # Coefficient conversion: QLaurent <-> sympy
    # ------------------------------------------------------------------

    def _qlaurent_to_sympy(self, coeff: QLaurent) -> sp.Expr:
        """Convert a :class:`QLaurent` to a sympy expression in ``self.q_sym``.

        ``QLaurent`` stores ``{exponent: int_coefficient}``; the result
        is ``sum(c * q**e)`` as a sympy :class:`Add`.  The zero
        :class:`QLaurent` maps to ``sympy.Integer(0)``.

        Subclasses such as :class:`ir.qomega.QOmega3` use
        :class:`fractions.Fraction` coefficients (not just ``int``); we
        handle both via :func:`sympy.Rational` (which accepts ``int``,
        ``Fraction``, and ``str`` representations).  If
        :attr:`self.q_value` is set (e.g. an algebraic element such as
        ``omega``), the expression is *evaluated* at ``q = q_value``
        rather than kept symbolic in ``q_sym``; this lets the
        downstream Groebner computation run over the algebraic field
        ``Q(q_value)`` instead of the rational-function field
        ``Q(q)``.
        """
        if coeff.is_zero():
            return sp.Integer(0)
        terms = []
        for e, c in coeff.terms.items():
            # Use sp.Rational to handle both int and Fraction coefficients.
            coeff_sym = sp.Rational(c)
            terms.append(coeff_sym * self.q_sym ** sp.Integer(int(e)))
        expr = sp.Add(*terms)
        if self.q_value is not None:
            # q_value may be a QOmega3 object, a sympy expression, or a complex number.
            # Convert it to a sympy expression first.
            q_val_sympy = self._coerce_to_sympy(self.q_value)
            if q_val_sympy is not None:
                expr = expr.subs(self.q_sym, q_val_sympy)
                expr = sp.simplify(expr)
        return sp.expand(expr)

    @staticmethod
    def _coerce_to_sympy(val):
        """Convert a value (QOmega3, complex, sympy expr, etc.) to a sympy expression."""
        if val is None:
            return None
        if isinstance(val, sp.Expr):
            return val
        # QOmega3 / QLaurent: use to_complex() if available
        if hasattr(val, 'to_complex'):
            c = val.to_complex()
            # nsimplify with real constants only, then express imaginary part
            # For omega = e^{2pi*i/3} = -1/2 + i*sqrt(3)/2
            real_part = c.real
            imag_part = c.imag
            r = sp.nsimplify(real_part, [sp.sqrt(3)])
            i = sp.nsimplify(imag_part / sp.sqrt(3).evalf(), [sp.sqrt(3)]) * sp.sqrt(3)
            return r + sp.I * i
        # Complex/float
        if isinstance(val, (complex, float)):
            c = complex(val)
            r = sp.nsimplify(c.real, [sp.sqrt(3)])
            i = sp.nsimplify(c.imag / sp.sqrt(3).evalf(), [sp.sqrt(3)]) * sp.sqrt(3)
            return r + sp.I * i
        # Try direct sympify
        try:
            return sp.sympify(val)
        except Exception:
            pass
        # Last resort: evaluate as complex and nsimplify
        try:
            c = complex(val)
            return sp.nsimplify(c, [sp.sqrt(3), sp.I])
        except Exception:
            return None

    def _sympy_to_qlaurent(self, expr: sp.Expr) -> QLaurent:
        """Convert a sympy expression in ``q`` (integer coeffs) to :class:`QLaurent`.

        The expression must be a Laurent polynomial in ``q`` with
        integer coefficients.  Rational coefficients are accepted only
        when their denominator is 1 (i.e. they reduce to integers).

        Raises :class:`ValueError` if the expression contains
        non-integer coefficients or unrecognised factors.
        """
        expr = sp.expand(expr)
        if expr == 0:
            return QLaurent({})
        terms_dict: dict = {}
        for term in expr.as_ordered_terms():
            coeff, factors = term.as_coeff_mul(self.q_sym)
            # `coeff` is the part of `term` that does not contain q_sym;
            # `factors` is a tuple of factors that each contain q_sym
            # (typically just powers of q_sym).
            coeff_int: Optional[int] = None
            if isinstance(coeff, sp.Integer):
                coeff_int = int(coeff)
            elif coeff.is_rational:
                # Try to reduce to an integer.
                r = sp.nsimplify(coeff)
                if isinstance(r, sp.Integer):
                    coeff_int = int(r)
            if coeff_int is None:
                raise ValueError(
                    f"_sympy_to_qlaurent: non-integer coefficient {coeff} "
                    f"in term {term} of {expr}"
                )
            q_exp = 0
            for f in factors:
                if f == self.q_sym:
                    q_exp += 1
                elif f.is_Pow and f.base == self.q_sym and f.exp.is_Integer:
                    q_exp += int(f.exp)
                else:
                    raise ValueError(
                        f"_sympy_to_qlaurent: unrecognised factor {f} "
                        f"in term {term} of {expr}"
                    )
            terms_dict[q_exp] = terms_dict.get(q_exp, 0) + coeff_int
        # Drop zero coefficients (defensive).
        terms_dict = {e: c for e, c in terms_dict.items() if c != 0}
        return QLaurent(terms_dict)

    # ------------------------------------------------------------------
    # Encoding: NC -> commutative
    # ------------------------------------------------------------------

    def encode_word(
        self,
        word: Union[tuple, Monomial],
        start: int = 0,
    ) -> sp.Expr:
        """Encode a NC word at starting position ``start``.

        Parameters
        ----------
        word : tuple of int, or :class:`Monomial`
            The NC word as a sequence of generator indices.
            ``()`` (the empty word) maps to ``sympy.Integer(1)``.
        start : int
            The starting position.  Must satisfy
            ``0 <= start`` and ``start + len(word) - 1 <= max_degree``.

        Returns
        -------
        sympy.Expr
            ``x_{word[0], start} * x_{word[1], start+1} * ... *
            x_{word[-1], start+len(word)-1}`` as a sympy :class:`Mul`.
            The empty word returns ``sympy.Integer(1)``.

        Examples
        --------
        >>> enc = LetterplaceEncoder(["x", "y"], max_degree=4)
        >>> enc.encode_word((0, 1), 0)
        x0_s0*x1_s1
        >>> enc.encode_word((0, 1, 0), 2)  # x0_s2 * x1_s3 * x0_s4 (sympy reorders factors)
        x0_s2*x0_s4*x1_s3
        >>> enc.encode_word((), 0)
        1
        """
        if isinstance(word, Monomial):
            word = word.gens
        word = tuple(word)
        if start < 0:
            raise ValueError(
                f"encode_word: start must be >= 0, got {start}"
            )
        if not word:
            return sp.Integer(1)
        end = start + len(word) - 1
        if end > self.max_degree:
            raise ValueError(
                f"encode_word: word of length {len(word)} starting at "
                f"position {start} would reach position {end}, exceeding "
                f"max_degree {self.max_degree}"
            )
        factors = []
        for k, i in enumerate(word):
            if not (0 <= i < self.n_gens):
                raise IndexError(
                    f"encode_word: generator index {i} out of range "
                    f"[0, {self.n_gens})"
                )
            factors.append(self._vars[i][start + k])
        return sp.Mul(*factors)

    def encode_polynomial(
        self,
        poly: Polynomial,
        start: int = 0,
    ) -> sp.Expr:
        """Encode an NC :class:`Polynomial` at starting position ``start``.

        Each term ``(coeff, monomial)`` becomes
        ``coeff_sympy * encode_word(monomial, start)``, and the results
        are summed.  The zero polynomial returns ``sympy.Integer(0)``.
        """
        if not poly.terms:
            return sp.Integer(0)
        sympy_terms = []
        for term in poly.terms:
            coeff = self._qlaurent_to_sympy(term.coeff)
            mono = self.encode_word(term.monomial, start)
            sympy_terms.append(coeff * mono)
        return sp.Add(*sympy_terms)

    def encode_relation(
        self,
        rule: RewriteRule,
        start: int = 0,
    ) -> sp.Expr:
        """Encode the relation ``LHS - RHS`` at starting position ``start``.

        Returns ``encode_word(rule.lhs, start) - encode_polynomial(rule.rhs, start)``
        as an expanded sympy expression.  This is a single generator of
        the letterplace ideal ``I_lp``.
        """
        lhs_enc = self.encode_word(rule.lhs, start)
        rhs_enc = self.encode_polynomial(rule.rhs, start)
        return sp.expand(lhs_enc - rhs_enc)

    def encode_presentation(self, pres: Presentation) -> list:
        """Encode all relations at all valid starting positions.

        For each rule with LHS length ``L``, the starting positions
        range over ``s = 0, 1, ..., max_degree - L`` (so that the
        encoded relation fits within ``[0, max_degree]``).

        Returns the list of commutative generators of the letterplace
        ideal ``I_lp``.
        """
        generators = []
        for rule in pres.rules:
            lhs_len = len(rule.lhs)
            if lhs_len == 0:
                # Defensive: parser forbids empty LHS, but skip just in case.
                continue
            max_start = self.max_degree - lhs_len
            if max_start < 0:
                # LHS longer than max_degree+1: no valid position.  Skip.
                continue
            for s in range(0, max_start + 1):
                generators.append(self.encode_relation(rule, s))
        return generators

    # ------------------------------------------------------------------
    # Commutative Groebner basis
    # ------------------------------------------------------------------

    def compute_groebner_basis(
        self,
        pres: Presentation,
        order: str = "grevlex",
        include_q: bool = False,
        domain=None,
    ) -> list:
        """Encode the presentation and compute the commutative Groebner basis.

        Parameters
        ----------
        pres : Presentation
            The NC algebra presentation.
        order : str
            Monomial order for the Groebner basis.  Default ``'grevlex'``
            (graded reverse lexicographic) is typically fastest.  Use
            ``'lex'`` for letterplace-friendly leading terms (the NC
            LHS monomial becomes the leading term, so reduction mirrors
            NC rewriting).  Other options: ``'grlex'``.
        include_q : bool
            If True, include ``q_sym`` as the *last* variable in the
            Groebner call (useful with ``order='lex'`` to get
            letterplace-friendly leading terms while keeping ``q`` as
            a variable rather than a coefficient).  If False (default),
            ``q_sym`` is treated as a symbolic coefficient (sympy uses
            the ``EX`` expression domain).
        domain : sympy domain, optional
            If set (e.g. ``sympy.QQ.algebraic_field(omega)``), the
            Groebner basis is computed over this coefficient domain.
            This requires that ``self.q_value`` be set so that
            coefficients are already elements of the domain.

        Returns
        -------
        list of sympy.Expr
            The Groebner basis polynomials (each expanded).  Returns
            ``[]`` if the presentation has no relations whose LHS fits
            within ``max_degree``.
        """
        gens = self.encode_presentation(pres)
        if not gens:
            return []
        if include_q:
            all_vars = self.full_variable_list()
        else:
            all_vars = list(self._all_vars)
        if domain is not None:
            gb = sp.groebner(gens, *all_vars, order=order, domain=domain)
        else:
            gb = sp.groebner(gens, *all_vars, order=order)
        return [sp.expand(p) for p in gb]

    # ------------------------------------------------------------------
    # Decoding: commutative -> NC
    # ------------------------------------------------------------------

    def decode_monomial(self, comm_mono: sp.Expr) -> tuple:
        """Decode a commutative monomial back to ``(NC_word, start_position)``.

        Parameters
        ----------
        comm_mono : sympy.Expr
            A single commutative monomial — either a :class:`sympy.Symbol`
            (one variable), a :class:`sympy.Mul` (product of variables),
            or :class:`sympy.Integer` ``1`` (the empty monomial).

        Returns
        -------
        (tuple of int, int)
            The NC word (as a tuple of generator indices) and the
            starting position (the minimum position among the variables).

        Raises
        ------
        ValueError
            If ``comm_mono`` contains non-letterplace variables, or
            variable powers > 1, or non-consecutive positions.

        Examples
        --------
        >>> enc = LetterplaceEncoder(["x", "y"], max_degree=4)
        >>> enc.decode_monomial(enc.encode_word((0, 1, 0), 2))
        ((0, 1, 0), 2)
        """
        # Single Symbol: x_{i,s} -> ((i,), s).
        if isinstance(comm_mono, sp.Symbol):
            name = comm_mono.name
            if name not in self._name_to_idx_pos:
                raise ValueError(
                    f"decode_monomial: unknown variable {name!r} in {comm_mono}"
                )
            i, s = self._name_to_idx_pos[name]
            return ((i,), s)

        # Integer 1: the empty monomial.  Convention: start = 0.
        if isinstance(comm_mono, sp.Integer):
            if int(comm_mono) == 1:
                return ((), 0)
            raise ValueError(
                f"decode_monomial: integer {comm_mono} is not a monomial"
            )

        # Pow at the top level (e.g. x0_s0**2 from sympy's auto-simplification
        # of x0_s0 * x0_s0).  Letterplace monomials are squarefree, so any
        # power > 1 is invalid.
        if isinstance(comm_mono, sp.Pow) and isinstance(
            comm_mono.base, sp.Symbol
        ):
            name = comm_mono.base.name
            if name not in self._name_to_idx_pos:
                raise ValueError(
                    f"decode_monomial: unknown variable {name!r} in {comm_mono}"
                )
            exp = comm_mono.exp
            if exp.is_Integer and int(exp) == 1:
                i, s = self._name_to_idx_pos[name]
                return ((i,), s)
            raise ValueError(
                f"decode_monomial: variable power {comm_mono} > 1 is not a "
                f"valid letterplace monomial"
            )

        # Mul: product of variables (possibly with a numeric coefficient
        # that should be 1 for a pure monomial — but we accept any
        # sign/integer coefficient here and ignore it, since the caller
        # is responsible for separating coefficients via
        # `decode_polynomial`).
        if isinstance(comm_mono, sp.Mul):
            pairs = []
            coeff_part = sp.Integer(1)
            for factor in comm_mono.args:
                if isinstance(factor, sp.Symbol):
                    name = factor.name
                    if name not in self._name_to_idx_pos:
                        raise ValueError(
                            f"decode_monomial: unknown variable {name!r} "
                            f"in {comm_mono}"
                        )
                    pairs.append(self._name_to_idx_pos[name])
                elif isinstance(factor, sp.Pow) and isinstance(
                    factor.base, sp.Symbol
                ):
                    # Power of a variable.  Letterplace monomials are
                    # squarefree (each position appears at most once),
                    # so powers > 1 are invalid.
                    if (
                        factor.base.name in self._name_to_idx_pos
                        and factor.exp.is_Integer
                        and int(factor.exp) > 1
                    ):
                        raise ValueError(
                            f"decode_monomial: variable power {factor} > 1 "
                            f"is not a valid letterplace monomial"
                        )
                    raise ValueError(
                        f"decode_monomial: unrecognised power factor "
                        f"{factor} in {comm_mono}"
                    )
                elif isinstance(factor, (sp.Integer, sp.Rational)):
                    # A rational/integer factor (the coefficient); record
                    # it for sanity-checking (should be 1 for a pure
                    # monomial, but we tolerate -1 too).
                    coeff_part = coeff_part * factor
                else:
                    raise ValueError(
                        f"decode_monomial: unrecognised factor {factor} "
                        f"in {comm_mono}"
                    )
            if not pairs:
                # No variables, just a coefficient: treat as empty monomial.
                return ((), 0)
            pairs.sort(key=lambda p: p[1])
            positions = [p[1] for p in pairs]
            word = tuple(p[0] for p in pairs)
            if positions != list(
                range(positions[0], positions[0] + len(positions))
            ):
                raise ValueError(
                    f"decode_monomial: positions {positions} are not "
                    f"consecutive in {comm_mono}"
                )
            return (word, positions[0])

        raise ValueError(
            f"decode_monomial: unexpected expr type "
            f"{type(comm_mono).__name__}: {comm_mono}"
        )

    def decode_polynomial(self, comm_poly: sp.Expr) -> dict:
        """Decode a commutative polynomial to a dict ``{start_position: NC_Polynomial}``.

        The input is expanded and converted to a :class:`sympy.Poly` in
        the letterplace variables (with ``q`` kept in the coefficients).
        Each monomial is decoded via :meth:`decode_monomial` and grouped
        by its starting position.  Coefficients (sympy expressions in
        ``q``) are converted back to :class:`QLaurent`.

        Returns
        -------
        dict
            Mapping ``start_position -> Polynomial`` (NC polynomial).
            The zero polynomial returns ``{}``.

        Raises
        ------
        ValueError
            If a coefficient is not a Laurent polynomial in ``q`` with
            integer coefficients, or if a monomial has variable powers
            > 1 or non-consecutive positions.
        """
        comm_poly = sp.expand(comm_poly)
        if comm_poly == 0:
            return {}
        # Build a Poly in the x-variables only; q stays in the coefficients.
        # (sp.Poly treats any symbol not in the generator list as part of
        # the coefficient domain, which is what we want.)
        poly = sp.Poly(comm_poly, *self._all_vars)
        groups: dict = {}
        for mono_exp, coeff in poly.terms():
            if coeff == 0:
                continue
            ql_coeff = self._sympy_to_qlaurent(coeff)
            if ql_coeff.is_zero():
                continue
            # Build (gen_idx, position) pairs for variables with exponent 1.
            pairs = []
            for var_idx, exp in enumerate(mono_exp):
                if exp == 0:
                    continue
                if exp > 1:
                    raise ValueError(
                        f"decode_polynomial: variable "
                        f"{self._all_vars[var_idx]} appears with power "
                        f"{exp} > 1 (not a valid letterplace monomial)"
                    )
                name = self._all_vars[var_idx].name
                i, s = self._name_to_idx_pos[name]
                pairs.append((i, s))
            if not pairs:
                # Pure constant term (no x-variables): the empty NC word.
                word: tuple = ()
                start: int = 0
            else:
                pairs.sort(key=lambda p: p[1])
                positions = [p[1] for p in pairs]
                word = tuple(p[0] for p in pairs)
                if positions != list(
                    range(positions[0], positions[0] + len(positions))
                ):
                    raise ValueError(
                        f"decode_polynomial: positions {positions} are "
                        f"not consecutive in monomial {mono_exp}"
                    )
                start = positions[0]
            groups.setdefault(start, []).append(Term(ql_coeff, Monomial(word)))
        # Normalise each group into a single Polynomial.
        result: dict = {}
        for start, term_list in groups.items():
            poly_nc = Polynomial(term_list).normalize()
            if not poly_nc.is_zero():
                result[start] = poly_nc
        return result


__all__ = ["LetterplaceEncoder"]
