#!/usr/bin/env python3
"""
Minimal projective resolution of k over A = u_q(sl_2) at ℓ=3.

Computes HH²(A, k) = Ext²_A(k, k) via the minimal projective resolution,
using ONLY the multiplication table (pure linear algebra, no Gröbner bases).

Steps:
  1. Build multiplication table (27×27 matrices L_g for left multiplication)
  2. Compute primitive idempotents e_j = (1/ℓ) Σ q^{-ja} K^a
  3. Compute projective indecomposable modules P(j) = A · e_j
  4. Compute radical series of P(0): radⁱ(P(0)) = J · radⁱ⁻¹(P(0))
  5. Build minimal projective resolution: P₂ → P₁ → P₀ → k → 0
  6. Compute HHⁿ = Extⁿ(k, k) from the resolution
"""
import sys, cmath, math, time
import numpy as np
from fractions import Fraction
sys.path.insert(0, '/home/z/my-project/hopf-decoherence/scripts')

ELL = 3
Q = cmath.exp(2j * math.pi / ELL)
Q_INV = Q ** (-1)
D = Q - Q_INV
DIM = ELL ** 3  # 27

def idx(a, b, c):
    return a * ELL * ELL + b * ELL + c

def from_idx(i):
    return i // (ELL*ELL), (i // ELL) % ELL, i % ELL

def weight(i):
    a, b, c = from_idx(i)
    return (2*b - 2*c) % ELL

def build_mult_table():
    from verify_sl2_hh2 import build_multiplication_table
    return build_multiplication_table()

def build_left_action_matrices(mult):
    """Build L_g[i] = matrix of left-multiplication by basis[i], shape (DIM, DIM).
    L_g[i] @ v = (basis[i] * v) as a vector."""
    L = np.zeros((DIM, DIM, DIM), dtype=complex)
    for i in range(DIM):
        for j in range(DIM):
            for k in range(DIM):
                L[i, j, k] = mult[k, i, j]  # mult[k,i,j] = coeff of basis[k] in (basis[i]*basis[j])
        # Wait: (basis[i] * basis[j]) = Σ_k mult[k,i,j] * basis[k]
        # So L_g[i] @ e_j = Σ_k mult[k,i,j] * e_k
        # This means L_g[i][k, j] = mult[k, i, j]
    return L

def compute_idempotents():
    """Compute primitive idempotents e_j = (1/ℓ) Σ_{a=0}^{ℓ-1} q^{-ja} K^a.
    Returns e_j as vectors in C^DIM."""
    e = []
    for j in range(ELL):
        v = np.zeros(DIM, dtype=complex)
        for a in range(ELL):
            # K^a is basis[idx(a, 0, 0)]
            coeff = Q ** (-j * a) / ELL
            v[idx(a, 0, 0)] += coeff
        e.append(v)
    return e

def compute_projective_indecomposable(L, e_j):
    """P(j) = A · e_j (left ideal). Compute as the column space of Σ_i L_g[i] · e_j[i].
    Actually, P(j) = A · e_j = {a · e_j : a ∈ A} = span of all (basis[i] · e_j).
    As a matrix: P(j) = Σ_i L_g[i] · e_j[i] ... no.
    
    P(j) = A · e_j is the image of right-multiplication by e_j.
    Right-multiplication by e_j: R_{e_j}(a) = a · e_j.
    R_{e_j} = Σ_i e_j[i] · R_g[i] where R_g[i] is right-multiplication by basis[i].
    
    R_g[i][k, j] = mult[k, j, i]  (since basis[j] * basis[i] = Σ_k mult[k,j,i] basis[k])
    
    So P(j) = column space of R_{e_j} = column space of Σ_i e_j[i] * R_g[i].
    """
    # Build right-multiplication by e_j
    R_ej = np.zeros((DIM, DIM), dtype=complex)
    for i in range(DIM):
        if abs(e_j[i]) > 1e-14:
            # R_g[i] has entries R_g[i][k, j] = mult[k, j, i]
            R_ej += e_j[i] * mult[:, :, i]  # Wait, this is wrong shape.
    # Actually: R_{e_j} = Σ_i e_j[i] * (matrix with [k,j] = mult[k,j,i])
    # mult[k, j, i] = coefficient of basis[k] in (basis[j] * basis[i])
    # So (R_{e_j})[k, j] = Σ_i e_j[i] * mult[k, j, i] = (basis[j] * e_j)[k]
    # This is just: for each j, compute basis[j] * e_j as a vector, and put it as column j.
    R_ej = np.zeros((DIM, DIM), dtype=complex)
    for j in range(DIM):
        # basis[j] * e_j = Σ_i e_j[i] * (basis[j] * basis[i]) = Σ_i e_j[i] * Σ_k mult[k,j,i] basis[k]
        col = np.zeros(DIM, dtype=complex)
        for i in range(DIM):
            if abs(e_j[i]) > 1e-14:
                col += e_j[i] * mult[:, j, i]
        R_ej[:, j] = col
    
    # P(j) = column space of R_ej
    # Compute via SVD
    U, s, Vh = np.linalg.svd(R_ej, full_matrices=False)
    rank = np.sum(s > 1e-10 * (s[0] if len(s) > 0 else 1))
    return U[:, :rank], rank

def compute_jacobom_radical(L, mult):
    """Compute the Jacobson radical J = ker(ε) ∩ nilpotent ideal.
    For u_q(sl_2), J = ker(ε) = augmentation ideal.
    J = span{basis[i] : ε(basis[i]) = 0} = all basis elements except 1 = K^0 E^0 F^0.
    But more precisely, J is the ideal generated by E, F, K-1.
    
    Actually, for a finite-dimensional Hopf algebra over C, the Jacobson radical
    equals the augmentation ideal's nilpotent part. For u_q(sl_2) at ℓ=3:
    J = span{E^b F^c K^a : (b,c) ≠ (0,0)} ∪ {K^a - 1 : a > 0}
    
    More precisely: J is generated (as a two-sided ideal) by E, F, and K-1.
    Since K is invertible (K^3=1), K-1 generates the same ideal as {K-1, K^2-1}.
    
    For the computation: J = ker(ε) where ε(K^a E^b F^c) = 1 if b=c=0 else 0.
    This is a vector subspace of A, but NOT an ideal by itself. The Jacobson
    radical is the LARGEST nilpotent ideal contained in ker(ε).
    
    For u_q(sl_2), J = ker(ε) IS nilpotent (since E, F are nilpotent and K-1
    is nilpotent in the quotient). So J = ker(ε).
    """
    eps = np.zeros(DIM, dtype=complex)
    for a in range(ELL):
        eps[idx(a, 0, 0)] = 1.0
    
    # J = ker(ε) as a vector space
    # But J as an IDEAL is the ideal generated by E, F, K-1.
    # For the projective resolution, we need J as a left module acting on P(j).
    # J * P(j) = span of all (j_elem * p) where j_elem ∈ J, p ∈ P(j).
    
    # Actually, the radical of P(j) is J * P(j) (the left action of J on P(j)).
    # J is the ideal generated by E, F, K-1. As a vector space, J = ker(ε).
    # But the IDEAL J is not the same as the vector space ker(ε) — it's the
    # ideal GENERATED by ker(ε).
    
    # For u_q(sl_2) at ℓ=3: the ideal generated by E is the span of all
    # products containing E. Since E^3 = 0, this is finite.
    # Similarly for F. And K-1 = K - 1.
    
    # The simplest approach: J = ker(ε) as a set of vectors. Check if J is nilpotent.
    # J * J = span of all products j1 * j2 where j1, j2 ∈ J.
    # If J * J ⊊ J (strict), then J is nilpotent.
    
    # For u_q(sl_2), J = span of all basis elements except K^0 E^0 F^0 = 1.
    # dim J = 26.
    
    # Let's just use J = ker(ε) = span{basis[i] : i ≠ idx(0,0,0)}.
    J_basis = [i for i in range(DIM) if abs(eps[i]) < 1e-12]
    return J_basis, eps

def radical_of_module(L, P_basis, J_basis):
    """Compute rad(P) = J · P where J is the Jacobson radical and P is a left module.
    
    P is given as a set of basis vectors (indices into A).
    J · P = span of all (j * p) where j ∈ J, p ∈ P.
    
    Returns the basis of rad(P) as a matrix (columns are basis vectors in C^DIM).
    """
    # Build the matrix whose columns are all products j * p for j in J, p in P
    products = []
    for j_idx in J_basis:
        for p_idx in P_basis:
            # j * p = Σ_k mult[k, j_idx, p_idx] * basis[k]
            col = mult[:, j_idx, p_idx]
            if np.linalg.norm(col) > 1e-14:
                products.append(col)
    
    if not products:
        return np.zeros((DIM, 0), dtype=complex)
    
    M = np.array(products).T  # shape (DIM, n_products)
    # Column space = rad(P)
    U, s, Vh = np.linalg.svd(M, full_matrices=False)
    rank = np.sum(s > 1e-10 * (s[0] if len(s) > 0 else 1))
    return U[:, :rank]

def decompose_into_simples(module_basis, idempotents, L):
    """Decompose a module into simple modules using the idempotents.
    
    For each simple S(j), the multiplicity of S(j) in the module M is:
    m_j = dim(e_j * M) / dim(S(j))
    
    where e_j * M = {e_j * m : m ∈ M} is the e_j-isotypic component.
    """
    mults = []
    for j, e_j in enumerate(idempotents):
        # e_j * M: for each column m in module_basis, compute e_j * m
        # e_j * m = Σ_i e_j[i] * (basis[i] * m) = Σ_i e_j[i] * L_g[i] @ m
        # But L_g[i] @ m gives the vector basis[i] * m.
        # Actually: (e_j * m)[k] = Σ_i e_j[i] * mult[k, i, m_idx] for each m_idx in the basis of M.
        # This is: for each basis vector m of M, compute e_j * m as a vector.
        
        ej_M = []
        for col in range(module_basis.shape[1]):
            m = module_basis[:, col]
            # e_j * m = Σ_i e_j[i] * (basis[i] * m)
            result = np.zeros(DIM, dtype=complex)
            for i in range(DIM):
                if abs(e_j[i]) > 1e-14:
                    # basis[i] * m = L_g[i] @ m... but L_g[i] is left-mult by basis[i]
                    # L_g[i][k, j] = mult[k, i, j], so (L_g[i] @ m)[k] = Σ_j mult[k, i, j] * m[j]
                    result += e_j[i] * (mult[:, i, :] @ m)
            ej_M.append(result)
        
        if not ej_M:
            mults.append(0)
            continue
        
        M_ej = np.array(ej_M).T  # shape (DIM, n_cols)
        U, s, Vh = np.linalg.svd(M_ej, full_matrices=False)
        rank = np.sum(s > 1e-10 * (s[0] if len(s) > 0 else 1))
        # dim S(j) = j + 1 for u_q(sl_2)
        dim_S_j = j + 1
        multiplicity = rank // dim_S_j
        mults.append(multiplicity)
    
    return mults

def main():
    print("=== Minimal Projective Resolution of k over u_q(sl_2) at ℓ=3 ===")
    print(f"dim A = {DIM}")
    
    t0 = time.time()
    print("Building multiplication table...")
    global mult
    mult = build_mult_table()
    print(f"  Built in {time.time()-t0:.2f}s")
    
    # Build left action matrices
    print("Building left action matrices...")
    L = build_left_action_matrices(mult)
    
    # Compute idempotents
    print("Computing primitive idempotents...")
    idempotents = compute_idempotents()
    for j, e in enumerate(idempotents):
        nz = np.sum(np.abs(e) > 1e-14)
        print(f"  e_{j}: {nz} nonzero entries")
    
    # Verify: e_i * e_j = δ_{ij} * e_j
    print("Verifying idempotent orthogonality...")
    for i in range(ELL):
        for j in range(ELL):
            # e_i * e_j = Σ_k e_i[k] * Σ_l e_j[l] * (basis[k] * basis[l])
            prod = np.zeros(DIM, dtype=complex)
            for k in range(DIM):
                if abs(idempotents[i][k]) > 1e-14:
                    for l in range(DIM):
                        if abs(idempotents[j][l]) > 1e-14:
                            prod += idempotents[i][k] * idempotents[j][l] * mult[:, k, l]
            expected = idempotents[j] if i == j else np.zeros(DIM, dtype=complex)
            err = np.linalg.norm(prod - expected)
            if err > 1e-10:
                print(f"  WARNING: e_{i} * e_{j} error = {err:.2e}")
    print("  Idempotents verified.")
    
    # Compute projective indecomposable modules
    print("Computing projective indecomposable modules P(j)...")
    P_basis_list = []
    P_dims = []
    for j in range(ELL):
        P_j, dim_P_j = compute_projective_indecomposable(L, idempotents[j])
        P_basis_list.append(P_j)
        P_dims.append(dim_P_j)
        print(f"  P({j}): dim = {dim_P_j}")
    
    # Verify: Σ_j dim S(j) * dim P(j) = dim A
    total = sum((j+1) * P_dims[j] for j in range(ELL))
    print(f"  Σ dim S(j) * dim P(j) = {total} (expected {DIM})")
    
    # Compute Jacobson radical
    print("Computing Jacobson radical J...")
    J_basis, eps = compute_jacobom_radical(L, mult)
    print(f"  dim J = {len(J_basis)} (expected {DIM - 1} = 26)")
    
    # Compute radical series of P(0)
    print("Computing radical series of P(0)...")
    P0 = P_basis_list[0]
    P0_indices = list(range(DIM))  # all basis elements are candidates
    
    rad = P0
    rad_series = [rad]
    print(f"  rad⁰(P(0)): dim = {rad.shape[1]}")
    
    for layer in range(1, 10):
        # rad^layer(P(0)) = J * rad^{layer-1}(P(0))
        # J * P = span of all (j * p) where j ∈ J, p ∈ rad^{layer-1}
        new_rad = radical_of_module(L, list(range(DIM)), J_basis)  # This is wrong — need to use the actual basis of rad
        
        # Actually, J * M = span of all (j * m) where j ∈ J_basis, m ∈ M (columns of rad)
        products = []
        for j_idx in J_basis:
            for col in range(rad.shape[1]):
                m = rad[:, col]
                # j * m = mult[:, j_idx, :] @ m
                prod = mult[:, j_idx, :] @ m
                if np.linalg.norm(prod) > 1e-14:
                    products.append(prod)
        
        if not products:
            new_rad = np.zeros((DIM, 0), dtype=complex)
        else:
            M_prod = np.array(products).T
            U, s, Vh = np.linalg.svd(M_prod, full_matrices=False)
            rank = np.sum(s > 1e-10 * (s[0] if len(s) > 0 else 1))
            new_rad = U[:, :rank]
        
        print(f"  rad^{layer}(P(0)): dim = {new_rad.shape[1]}")
        if new_rad.shape[1] == 0:
            break
        rad = new_rad
        rad_series.append(rad)
    
    # The Loewy layers: L_i = rad^i / rad^{i+1}
    print("\nLoewy layers of P(0):")
    for i in range(len(rad_series) - 1):
        dim_layer = rad_series[i].shape[1] - rad_series[i+1].shape[1]
        print(f"  L_{i}: dim = {dim_layer}")
    if rad_series:
        print(f"  L_{len(rad_series)-1}: dim = {rad_series[-1].shape[1]}")
    
    # Decompose each Loewy layer into simples
    print("\nDecomposing Loewy layers into simples...")
    for i in range(len(rad_series) - 1):
        # The layer is rad^i / rad^{i+1}. We need to find the composition factors.
        # For the projective resolution, we need the radical, not the Loewy layers.
        pass
    
    # Build the minimal projective resolution of k = S(0)
    print("\n=== Minimal Projective Resolution of k = S(0) ===")
    
    # P_0 = P(0), d_0: P(0) → k (augmentation)
    P0 = P_basis_list[0]
    dim_P0 = P0.shape[1]
    print(f"P_0 = P(0), dim = {dim_P0}")
    
    # K_1 = ker(d_0) = rad(P(0)) = J * P(0)
    # Compute J * P(0)
    products = []
    for j_idx in J_basis:
        for col in range(P0.shape[1]):
            m = P0[:, col]
            prod = mult[:, j_idx, :] @ m
            if np.linalg.norm(prod) > 1e-14:
                products.append(prod)
    M_prod = np.array(products).T
    U, s, Vh = np.linalg.svd(M_prod, full_matrices=False)
    rank = np.sum(s > 1e-10 * (s[0] if len(s) > 0 else 1))
    K1 = U[:, :rank]
    dim_K1 = K1.shape[1]
    print(f"K_1 = rad(P(0)), dim = {dim_K1}")
    
    # Decompose K_1 into simples: count multiplicities of S(j) in K_1
    print("Decomposing K_1 into simples...")
    mults_K1 = decompose_into_simples(K1, idempotents, L)
    print(f"  Composition factors of K_1: S(0)^{mults_K1[0]}, S(1)^{mults_K1[1]}, S(2)^{mults_K1[2]}")
    
    # P_1 = projective cover of K_1 = ⊕_j P(j)^{mult_K1[j]}
    dim_P1 = sum(mults_K1[j] * P_dims[j] for j in range(ELL))
    print(f"P_1 = ⊕ P(j)^{{m_j}}, dim = {dim_P1}")
    
    # d_1: P_1 → K_1 ⊂ P_0
    # K_2 = ker(d_1) = rad(P_1) (since P_1 is projective, the kernel is the radical)
    # Actually, K_2 = ker(d_1) where d_1 is the projective cover map.
    # For a minimal projective resolution, K_2 = rad(P_1) = J * P_1.
    # But we need to compute this more carefully.
    
    # For the minimal resolution: the kernel of d_n is always in the radical of P_n.
    # K_{n+1} = ker(d_n) = rad(P_n) (for minimal resolution).
    # So K_2 = rad(P_1).
    
    # Compute K_2 = rad(P_1) = J * P_1
    # P_1 = ⊕ P(j)^{m_j}. rad(P_1) = ⊕ rad(P(j))^{m_j}.
    # dim rad(P(j)) = dim P(j) - dim S(j) (the top is S(j))
    dim_K2 = sum(mults_K1[j] * (P_dims[j] - (j+1)) for j in range(ELL))
    print(f"K_2 = rad(P_1), dim = {dim_K2}")
    
    # Decompose K_2 into simples
    # rad(P(j)) has composition factors S(j') for j' ≠ j (the non-top factors)
    # For u_q(sl_2) at ℓ=3, the Loewy structure of P(j) is:
    # P(0): top=S(0), rad=S(2), rad²=S(1), rad³=S(0) (if dim P(0) = 1+3+2+1 = 7? No...)
    # Actually, I need to compute this from the radical series.
    
    # For now, let's compute the Ext dimensions using the formula:
    # HH^n = dim Hom(P_n, k) / im(Hom(P_{n+1}, k))
    # Hom(P(j), k) = e_0 * P(j) which has dimension = multiplicity of S(0) in P(j)
    
    # Compute multiplicity of S(0) in each P(j)
    print("\nMultiplicities of S(0) in P(j):")
    mult_S0_in_P = []
    for j in range(ELL):
        m = decompose_into_simples(P_basis_list[j], idempotents, L)
        print(f"  P({j}) has S(0) multiplicity = {m[0]}")
        mult_S0_in_P.append(m[0])
    
    # HH^0 = dim Hom(P_0, k) / im(Hom(P_1, k) → Hom(P_0, k))
    # For the minimal resolution:
    # HH^0 = dim S(0) = 1 (always)
    # HH^1 = dim Hom(P_1, k) / im(d_1*)
    #   dim Hom(P_1, k) = Σ_j mult_K1[j] * mult_S0_in_P[j]
    #   im(d_1*) has dimension = rank of d_1 ⊗ k
    #   For minimal resolution: im(d_1*) = 0 (since d_1 maps into rad(P_0), and Hom(rad(P_0), k) = 0)
    #   So HH^1 = dim Hom(P_1, k) = Σ_j mult_K1[j] * mult_S0_in_P[j]
    
    dim_Hom_P1_k = sum(mults_K1[j] * mult_S0_in_P[j] for j in range(ELL))
    print(f"\ndim Hom(P_1, k) = {dim_Hom_P1_k}")
    print(f"HH^1 = {dim_Hom_P1_k} (since im(d_1*) = 0 for minimal resolution)")
    
    # HH^2 = dim Hom(P_2, k) / im(d_2*)
    # Need: composition factors of K_2, then P_2 = ⊕ P(j)^{mult_K2[j]}
    # dim Hom(P_2, k) = Σ_j mult_K2[j] * mult_S0_in_P[j]
    # im(d_2*) = 0 for minimal resolution
    # So HH^2 = Σ_j mult_K2[j] * mult_S0_in_P[j]
    
    # To get mult_K2, we need to decompose K_2 = rad(P_1) into simples.
    # rad(P(j)) has the same composition factors as P(j) minus the top S(j).
    # So mult_K2[i] = Σ_j mult_K1[j] * (mult_S(i) in P(j) - δ_{ij})
    
    # Get full composition factor multiplicities of each P(j)
    print("\nFull composition factors of P(j):")
    comp_factors = []
    for j in range(ELL):
        m = decompose_into_simples(P_basis_list[j], idempotents, L)
        print(f"  P({j}): S(0)^{m[0]}, S(1)^{m[1]}, S(2)^{m[2]}")
        comp_factors.append(m)
    
    # K_2 = rad(P_1) = ⊕_j rad(P(j))^{mult_K1[j]}
    # rad(P(j)) has composition factors: comp_factors[j][i] - δ_{ij} for each simple S(i)
    mults_K2 = [0] * ELL
    for j in range(ELL):
        for i in range(ELL):
            mults_K2[i] += mults_K1[j] * (comp_factors[j][i] - (1 if i == j else 0))
    
    print(f"\nComposition factors of K_2: S(0)^{mults_K2[0]}, S(1)^{mults_K2[1]}, S(2)^{mults_K2[2]}")
    
    dim_Hom_P2_k = sum(mults_K2[j] * mult_S0_in_P[j] for j in range(ELL))
    print(f"dim Hom(P_2, k) = {dim_Hom_P2_k}")
    print(f"HH^2 = {dim_Hom_P2_k} (since im(d_2*) = 0 for minimal resolution)")
    print(f"\nExpected HH^2 = 3")
    print(f"MATCH: {dim_Hom_P2_k == 3}")
    
    return dim_Hom_P2_k

if __name__ == "__main__":
    result = main()
    print(f"\nFinal answer: dim HH² = {result}")
