#!/usr/bin/env python3
"""
Bar-complex computation of HH^2(B+(u_q(sl_3)), C) at ell = 3.

B+(sl_3) is the positive Borel subalgebra generated by K1, K2, E1, E2.
PBW basis (standard order for U_q^+(sl_3)):  K1^a K2^b E1^c E12^e E2^d
where E12 = E1 E2 - q E2 E1 is the root vector for alpha_1 + alpha_2.

Dimension at ell=3: 3^5 = 243.

Relations (q = e^{2 pi i / 3}, so q^3 = 1, q + q^{-1} = -1):
  K1^ell = K2^ell = 1
  E1^ell = E2^ell = E12^ell = 0
  K1 E1 K1^{-1} = q^2 E1,   K1 E2 K1^{-1} = q^{-1} E2,   K1 E12 K1^{-1} = q E12
  K2 E1 K2^{-1} = q^{-1} E1, K2 E2 K2^{-1} = q^2 E2,    K2 E12 K2^{-1} = q E12
  E12 = E1 E2 - q E2 E1   (definition)
  Quantum Serre: E1^2 E2 - (q + q^{-1}) E1 E2 E1 + E2 E1^2 = 0  =>  E1^2 E2 + E1 E2 E1 + E2 E1^2 = 0
                 E2^2 E1 - (q + q^{-1}) E2 E1 E2 + E1 E2^2 = 0  =>  E2^2 E1 + E2 E1 E2 + E1 E2^2 = 0

PBW commutation relations (derived from the above):
  E2 E1 = q^{-1} E1 E2 - q^{-1} E12                     ... (i)
  E12 E1 = q^{-1} E1 E12  (since E12 has weight alpha_1+alpha_2 and E1 has weight alpha_1;
                           the commutator [E12, E1] in the Nichols algebra is a higher root vector
                           which vanishes for sl_3)        ... (ii) [TO VERIFY]
  E2 E12 = q^{-1} E12 E2  (similarly)                    ... (iii) [TO VERIFY]

Let me verify (ii) and (iii) from the definitions and Serre:
  E12 E1 = (E1 E2 - q E2 E1) E1 = E1 E2 E1 - q E2 E1^2.
  Using E2 E1 = q^{-1} E1 E2 - q^{-1} E12:
    E1 E2 E1 = E1 (q^{-1} E1 E2 - q^{-1} E12) E1 ... wait, that's E1 (E2 E1).
    Let me redo: E1 E2 E1. We have E2 E1 = q^{-1} E1 E2 - q^{-1} E12, so
    E1 E2 E1 = E1 (E2 E1) = E1 (q^{-1} E1 E2 - q^{-1} E12) = q^{-1} E1^2 E2 - q^{-1} E1 E12.
  And E2 E1^2 = (E2 E1) E1 = (q^{-1} E1 E2 - q^{-1} E12) E1 = q^{-1} E1 E2 E1 - q^{-1} E12 E1.
  Substitute back into Serre: E1^2 E2 + E1 E2 E1 + E2 E1^2 = 0:
    E1^2 E2 + (q^{-1} E1^2 E2 - q^{-1} E1 E12) + (q^{-1} E1 E2 E1 - q^{-1} E12 E1) = 0.
    E1^2 E2 (1 + q^{-1}) + q^{-1} E1 E2 E1 - q^{-1} E1 E12 - q^{-1} E12 E1 = 0.
    Using 1 + q^{-1} = -q^{-2} (from 1 + q^{-1} + q^{-2} = 0):
    -q^{-2} E1^2 E2 + q^{-1} E1 E2 E1 - q^{-1} E1 E12 - q^{-1} E12 E1 = 0.
    Multiply by -q^2:
    E1^2 E2 - q E1 E2 E1 + q E1 E12 + q E12 E1 = 0.
    => q E12 E1 = -E1^2 E2 + q E1 E2 E1 - q E1 E12.
    => E12 E1 = -q^{-1} E1^2 E2 + E1 E2 E1 - E1 E12.
    Now substitute E1 E2 E1 = q^{-1} E1^2 E2 - q^{-1} E1 E12 (derived above):
    E12 E1 = -q^{-1} E1^2 E2 + (q^{-1} E1^2 E2 - q^{-1} E1 E12) - E1 E12
           = -q^{-1} E1 E12 - E1 E12 = -(1 + q^{-1}) E1 E12 = q^{-2} E1 E12.
    Since q^{-2} = q (because q^3 = 1): E12 E1 = q E1 E12.   ... (ii) VERIFIED (with q, not q^{-1}!)

  Similarly, E2 E12 = E2 (E1 E2 - q E2 E1) = E2 E1 E2 - q E2^2 E1.
  Using E2 E1 = q^{-1} E1 E2 - q^{-1} E12:
    E2 E1 E2 = (q^{-1} E1 E2 - q^{-1} E12) E2 = q^{-1} E1 E2^2 - q^{-1} E12 E2.
  So E2 E12 = q^{-1} E1 E2^2 - q^{-1} E12 E2 - q E2^2 E1.
  Serre II: E2^2 E1 + E2 E1 E2 + E1 E2^2 = 0 => E2^2 E1 = -E2 E1 E2 - E1 E2^2.
  E2 E1 E2 = (q^{-1} E1 E2 - q^{-1} E12) E2 = q^{-1} E1 E2^2 - q^{-1} E12 E2.
  So E2^2 E1 = -(q^{-1} E1 E2^2 - q^{-1} E12 E2) - E1 E2^2 = -q^{-1} E1 E2^2 + q^{-1} E12 E2 - E1 E2^2
             = -(1 + q^{-1}) E1 E2^2 + q^{-1} E12 E2 = q^{-2} E1 E2^2 + q^{-1} E12 E2 = q E1 E2^2 + q^{-1} E12 E2.
  Substitute back:
    E2 E12 = q^{-1} E1 E2^2 - q^{-1} E12 E2 - q (q E1 E2^2 + q^{-1} E12 E2)
           = q^{-1} E1 E2^2 - q^{-1} E12 E2 - q^2 E1 E2^2 - E12 E2
           = (q^{-1} - q^2) E1 E2^2 + (-q^{-1} - 1) E12 E2.
    q^{-1} - q^2 = q^2 - q^2 = 0 (since q^{-1} = q^2). Good, the E1 E2^2 term vanishes.
    -q^{-1} - 1 = -q^2 - 1 = q (since 1 + q + q^2 = 0 => -1 - q^2 = q).
    So E2 E12 = q E12 E2.   ... (iii) VERIFIED (with q, not q^{-1}!)

So the commutation relations for PBW order E1^c E12^e E2^d are:
  E2 E1  = q^{-1} E1 E2 - q^{-1} E12
  E12 E1 = q E1 E12
  E2 E12 = q E12 E2
"""
import cmath, math, time
import numpy as np
from scipy import sparse


ELL = 3
Q = cmath.exp(2j * math.pi / ELL)
Q_INV = Q ** (-1)
# q + q^{-1} = -1 for q = e^{2pi i / 3}
assert abs(Q + Q_INV - (-1)) < 1e-12
DIM = ELL ** 5  # 243


def idx(a, b, c, e, d):
    """Index of K1^a K2^b E1^c E12^e E2^d (PBW order: E1, E12, E2)."""
    return a * (ELL**4) + b * (ELL**3) + c * (ELL**2) + e * ELL + d


def from_idx(i):
    return i // (ELL**4), (i // (ELL**3)) % ELL, (i // (ELL**2)) % ELL, (i // ELL) % ELL, i % ELL


def weight(i):
    """2D weight (alpha_1, alpha_2) components mod ell, using the root lattice.
    E1 has weight alpha_1 = (1, 0), E2 has weight alpha_2 = (0, 1), E12 has weight (1, 1).
    K1, K2 have weight (0, 0).
    So weight of K1^a K2^b E1^c E12^e E2^d = c*(1,0) + e*(1,1) + d*(0,1) = (c+e, e+d).
    """
    a, b, c, e, d = from_idx(i)
    w1 = (c + e) % ELL
    w2 = (e + d) % ELL
    return (w1, w2)


# ============================================================
# E-part multiplication (E1^c E12^e E2^d order)
# Elements are dicts {(c, e, d): coeff}.
# ============================================================

def e_mult_by_E1_left(elem):
    """Multiply E-part by E1 on the left: E1 * (E1^c E12^e E2^d) = E1^{c+1} E12^e E2^d.
    E1 commutes trivially with itself, and we're using PBW order E1^c E12^e E2^d,
    so E1 just adds to the c-exponent. Vanishes if c+1 == ell.
    """
    new = {}
    for (c, e, d), v in elem.items():
        if c + 1 < ELL:
            key = (c + 1, e, d)
            new[key] = new.get(key, 0) + v
    return {k: v for k, v in new.items() if abs(v) > 1e-13}


def e_mult_by_E12_left(elem):
    """Multiply E-part by E12 on the left.
    E12 * E1^c = q^c E1^c E12 (from E12 E1 = q E1 E12, so E12 E1^c = q^c E1^c E12).
    Then E12 * E12 = E12^2 (just adds to e-exponent).
    Then E12 * E2^d: from E2 E12 = q E12 E2 => E12 E2 = q^{-1} E2 E12.
    So E12 E2^d = q^{-d} E2^d E12. But we want PBW form E1^c E12^e E2^d,
    so E2^d E12 is NOT in PBW form — we need E12 E2^d = q^{-d} E2^d E12,
    and E2^d E12 has E2 before E12, which is wrong order.
    Actually wait: E12 E2 = q^{-1} E2 E12 means E12 E2^d = q^{-d} E2^d E12.
    But E2^d E12 is in order E2^d E12, which in our PBW (E1^c E12^e E2^d) would be
    E1^0 E12^1 E2^d with a phase... no, E2^d E12 means E2 first then E12,
    but our PBW order is E1^c E12^e E2^d, i.e., E12 BEFORE E2.
    So E2^d E12 = q^{d} E12 E2^d (inverting the relation E12 E2 = q^{-1} E2 E12).
    Therefore E12 * (E1^c E12^e E2^d) = q^c * q^{-d... wait let me redo.

    E12 * E1^c E12^e E2^d:
    First, E12 * E1^c = q^c E1^c E12 (using E12 E1 = q E1 E12 repeatedly).
    So E12 * E1^c E12^e E2^d = q^c E1^c (E12 * E12^e E2^d) = q^c E1^c E12^{e+1} E2^d.
    Wait, does E12 commute with E2^d in a way that lets us just add to e?
    E12 E2 = q^{-1} E2 E12, so E12 E2^d = q^{-d} E2^d E12. To put in PBW form
    (E12 before E2), we use E2^d E12 = q^d E12 E2^d. So E12 E2^d = q^{-d} * q^d E12 E2^d = E12 E2^d.
    That's trivially true — I confused myself.

    Let me redo carefully. E12 * X where X = E1^c E12^e E2^d (in PBW order).
    E12 E1^c: use E12 E1 = q E1 E12 (relation ii). So E12 E1 = q E1 E12.
    E12 E1^2 = E12 E1 E1 = q E1 E12 E1 = q E1 (q E1 E12) = q^2 E1^2 E12.
    In general E12 E1^c = q^c E1^c E12.
    E12 E12^e = E12^{e+1} (trivial).
    E12 E2^d: E12 E2 = q^{-1} E2 E12 (from E2 E12 = q E12 E2). So E12 E2 = q^{-1} E2 E12.
    E12 E2^d = q^{-d} E2^d E12. Now E2^d E12 is NOT in PBW form (E2 before E12).
    Convert: E2 E12 = q E12 E2, so E2^d E12 = ... this requires commuting E2 past E12.
    E2^d E12 = q^{-d} E12 E2^d? No: E2 E12 = q E12 E2 => E12 E2 = q^{-1} E2 E12.
    So E2^d E12 = E2^{d-1} (E2 E12) = E2^{d-1} (q E12 E2) = q E2^{d-1} E12 E2.
    Continue: E2^{d-1} E12 = q E2^{d-2} E12 E2, so E2^d E12 = q^2 E2^{d-2} E12 E2^2.
    In general: E2^d E12 = q^d E12 E2^d.
    So E12 E2^d = q^{-d} E2^d E12 = q^{-d} * q^d E12 E2^d = E12 E2^d. (Trivially consistent.)
    Hmm, that means E12 commutes with E2^d with phase 1? Let me recheck.
    E12 E2 = q^{-1} E2 E12. So E12 E2^2 = E12 E2 E2 = q^{-1} E2 E12 E2 = q^{-1} E2 (q^{-1} E2 E12) = q^{-2} E2^2 E12.
    Then E2^2 E12 = q^2 E12 E2^2 (inverting), so E12 E2^2 = q^{-2} * q^2 E12 E2^2 = E12 E2^2. (Tautology again.)
    The issue: I'm trying to compute E12 E2^d directly. Let me just do it by induction.
    E12 E2^0 = E12 (trivial).
    E12 E2^{d+1} = (E12 E2^d) E2 = (q^{-d} E2^d E12) E2 [by induction, in NON-PBW form]
                 = q^{-d} E2^d (E12 E2) = q^{-d} E2^d (q^{-1} E2 E12) = q^{-(d+1)} E2^{d+1} E12.
    So E12 E2^d = q^{-d} E2^d E12 (in NON-PBW form). To convert to PBW (E12 before E2):
    E2^d E12 = q^d E12 E2^d (by the inverted relation). So:
    E12 E2^d = q^{-d} * q^d E12 E2^d = E12 E2^d. Hmm, that gives phase 1, which is wrong.

    I think I'm confusing myself. Let me just directly say:
    E12 E2^d, in PBW form (E1^c E12^e E2^d), should be q^{-d} E1^0 E12^1 E2^d... no wait.
    E12 E2 = q^{-1} E2 E12. This means E12 E2 = (q^{-1}) E2 E12. The PBW form has E12 BEFORE E2,
    so we need to rewrite E2 E12 as something times E12 E2. From E12 E2 = q^{-1} E2 E12,
    we get E2 E12 = q E12 E2. So E12 E2 is already "E12 before E2", which IS PBW form!
    So E12 E2 = q^{-1} E2 E12 means... no, that's NOT PBW form (E2 is before E12 on the RHS).

    OK I think the relation E12 E2 = q^{-1} E2 E12 means: when E12 is on the LEFT of E2,
    we can swap them at the cost of a phase q^{-1}, putting E2 on the left and E12 on the right.
    But PBW order is E1, E12, E2 — i.e., E12 should be to the LEFT of E2.
    So "E12 E2" is ALREADY in PBW form (E12 left of E2). The relation tells us how to
    convert from "E2 E12" (non-PBW) to "E12 E2" (PBW): E2 E12 = q E12 E2.

    So when multiplying E12 * (E1^c E12^e E2^d):
    - E12 * E1^c = q^c E1^c E12 (PBW: E1^c E12, good)
    - E12 * E12^e = E12^{e+1} (PBW: E12^{e+1}, good)
    - E12 * E2^d = (E12 E2)^d? No, E12 * E2^d = E12 E2^d. This is E12 to the left of E2^d,
      which IS PBW form. So it stays as E12 E2^d = E1^0 E12^1 E2^d.
    Putting it together:
    E12 * (E1^c E12^e E2^d) = q^c * (E1^c E12) * E12^e * E2^d = q^c E1^c E12^{e+1} E2^d.
    Wait, but we also need E12 to pass through E12^e, which is trivial (they're the same generator).
    And E12 doesn't interact with E2^d because E12 is already to the left of E2^d.
    So: E12 * (E1^c E12^e E2^d) = q^c E1^c E12^{e+1} E2^d. Vanishes if e+1 == ell.
    """
    new = {}
    for (c, e, d), v in elem.items():
        if e + 1 < ELL:
            phase = Q ** c  # E12 E1^c = q^c E1^c E12
            key = (c, e + 1, d)
            new[key] = new.get(key, 0) + v * phase
    return {k: v for k, v in new.items() if abs(v) > 1e-13}


def e_mult_by_E2_left(elem):
    """Multiply E-part by E2 on the left.
    E2 * E1^c: use E2 E1 = q^{-1} E1 E2 - q^{-1} E12. So we need to commute E2 past E1^c,
    which generates E12 terms. This is the most complex case.

    E2 E1 = q^{-1} E1 E2 - q^{-1} E12.
    E2 E1^2 = (E2 E1) E1 = (q^{-1} E1 E2 - q^{-1} E12) E1
            = q^{-1} E1 (E2 E1) - q^{-1} E12 E1
            = q^{-1} E1 (q^{-1} E1 E2 - q^{-1} E12) - q^{-1} (q E1 E12)  [using E12 E1 = q E1 E12]
            = q^{-2} E1^2 E2 - q^{-2} E1 E12 - E1 E12
            = q E1^2 E2 - q E1 E12 - E1 E12    [q^{-2} = q since q^3 = 1]
            = q E1^2 E2 - (q + 1) E1 E12
            = q E1^2 E2 - (-q^{-1}) E1 E12     [q + 1 = -q^{-1}]
            = q E1^2 E2 + q^{-1} E1 E12.

    In general, E2 E1^c can be computed by induction, but it's messy.
    Let me use a recursive approach: define a function that, given a monomial E1^c E12^e E2^d,
    computes E2 * (that monomial) as a sum of PBW monomials.

    Base case: E2 * (E1^c E12^e E2^d).
    - If c > 0: E2 E1 = q^{-1} E1 E2 - q^{-1} E12, so
      E2 * E1^c = (q^{-1} E1 E2 - q^{-1} E12) E1^{c-1} = q^{-1} E1 (E2 E1^{c-1}) - q^{-1} E12 E1^{c-1}.
      Recurse on E2 E1^{c-1}. And E12 E1^{c-1} = q^{c-1} E1^{c-1} E12.
    - If c == 0: E2 * E12^e = (E2 E12) E12^{e-1} = q E12 E2 E12^{e-1} = q E12 (E2 E12^{e-1})... wait,
      E2 E12 = q E12 E2, so E2 E12^e = q^e E12^e E2. Then E2 E2^d = E2^{d+1}.
      So E2 * (E12^e E2^d) = q^e E12^e E2^{d+1}. Vanishes if d+1 == ell.
    """
    new = {}
    for (c, e, d), v in elem.items():
        # E2 * (E1^c E12^e E2^d)
        if c > 0:
            # E2 E1^c = q^{-1} E1 (E2 E1^{c-1}) - q^{-1} E12 E1^{c-1}
            #          = q^{-1} E1 (E2 E1^{c-1}) - q^{-1} q^{c-1} E1^{c-1} E12
            # We need to expand E2 E1^{c-1} recursively. To avoid infinite recursion,
            # expand iteratively.
            # Let's compute E2 E1^c as a sum of PBW monomials directly.
            terms = _e2_e1_power(c)  # returns {(c', e', d'): coeff} representing E2 E1^c in PBW form
            for (cp, ep, dp), vp in terms.items():
                # Now multiply by E12^e E2^d on the right
                # (E1^{cp} E12^{ep} E2^{dp}) * E12^e E2^d
                # E2^{dp} E12^e = q^{e*dp... no. E2 E12 = q E12 E2, so E2^{dp} E12^e = q^{e*dp} E12^e E2^{dp}.
                # Wait: E2 E12 = q E12 E2 means each E2 commutes past each E12 with phase q.
                # So E2^{dp} E12^e = q^{e * dp} E12^e E2^{dp}.
                # Hmm, that's not right either. E2 E12 = q E12 E2. So E2 E12^e = q^e E12^e E2 (one E2).
                # E2^2 E12^e = E2 (q^e E12^e E2) = q^e (E2 E12^e) E2 = q^e * q^e E12^e E2^2 = q^{2e} E12^e E2^2.
                # In general E2^{dp} E12^e = q^{e*dp} E12^e E2^{dp}.
                # So (E1^{cp} E12^{ep} E2^{dp}) * (E12^e E2^d)
                # = E1^{cp} E12^{ep} (E2^{dp} E12^e) E2^d
                # = E1^{cp} E12^{ep} (q^{e*dp} E12^e E2^{dp}) E2^d
                # = q^{e*dp} E1^{cp} E12^{ep+e} E2^{dp+d}.
                # Vanishes if ep+e >= ell or dp+d >= ell.
                if ep + e < ELL and dp + d < ELL:
                    phase = Q ** (e * dp)
                    key = (cp, ep + e, dp + d)
                    new[key] = new.get(key, 0) + v * vp * phase
        else:
            # c == 0: E2 * (E12^e E2^d) = q^e E12^e E2^{d+1}
            if d + 1 < ELL:
                phase = Q ** e
                key = (0, e, d + 1)
                new[key] = new.get(key, 0) + v * phase
    return {k: v for k, v in new.items() if abs(v) > 1e-13}


def _e2_e1_power(c):
    """Compute E2 * E1^c as a sum of PBW monomials {(c', e', d'): coeff}.
    E2 E1^0 = E2 = E1^0 E12^0 E2^1. So _e2_e1_power(0) = {(0, 0, 1): 1.0}.
    E2 E1 = q^{-1} E1 E2 - q^{-1} E12 = q^{-1} E1^1 E12^0 E2^1 - q^{-1} E1^0 E12^1 E2^0.
    E2 E1^c: use the recursion E2 E1^c = q^{-1} E1 (E2 E1^{c-1}) - q^{-1} q^{c-1} E1^{c-1} E12
                              = q^{-1} E1 (E2 E1^{c-1}) - q^{c-2} E1^{c-1} E12.
    """
    if c == 0:
        return {(0, 0, 1): 1.0}
    # Recurse
    prev = _e2_e1_power(c - 1)  # E2 E1^{c-1} in PBW form
    result = {}
    # Term 1: q^{-1} E1 * (E2 E1^{c-1})
    for (cp, ep, dp), v in prev.items():
        if cp + 1 < ELL:
            key = (cp + 1, ep, dp)
            result[key] = result.get(key, 0) + v * Q_INV
    # Term 2: -q^{c-2} E1^{c-1} E12
    # E1^{c-1} E12 is in PBW form (E1 first, then E12), so just (c-1, 1, 0).
    if c - 1 < ELL and 1 < ELL:
        key = (c - 1, 1, 0)
        phase = -Q ** (c - 2)
        result[key] = result.get(key, 0) + phase
    return {k: v for k, v in result.items() if abs(v) > 1e-13}


def e_multiply(left, right):
    """Multiply two E-parts (both in PBW form). left * right.
    For a monomial E1^{c2} E12^{e2} E2^{d2} in `right`, we compute
    left * (E1^{c2} E12^{e2} E2^{d2}) by applying the generators LEFT TO RIGHT:
    first E1^{c2} (leftmost), then E12^{e2}, then E2^{d2} (rightmost).
    i.e., ((left * E1^{c2}) * E12^{e2}) * E2^{d2}.
    """
    result = {}
    for (c2, e2, d2), v2 in right.items():
        acc = {mon: coeff for mon, coeff in left.items()}  # copy
        # Apply E1^{c2} on the right (leftmost generator of the right monomial)
        for _ in range(c2):
            acc = e_mult_by_E1_right(acc)
        # Apply E12^{e2} on the right
        for _ in range(e2):
            acc = e_mult_by_E12_right(acc)
        # Apply E2^{d2} on the right (rightmost generator)
        for _ in range(d2):
            acc = e_mult_by_E2_right(acc)
        # Add to result with coefficient v2
        for mon, coeff in acc.items():
            result[mon] = result.get(mon, 0) + coeff * v2
    return {k: v for k, v in result.items() if abs(v) > 1e-13}


def e_mult_by_E1_right(elem):
    """Multiply E-part by E1 on the right: (E1^c E12^e E2^d) * E1.
    E2^d E1: commute E2 past E1, generating E12 terms. Same complexity as E2 E1^c but reversed.
    E12^e E1: E12 E1 = q E1 E12, so E12^e E1 = q^e E1 E12^e. But this puts E1 to the LEFT of E12,
    which means we need to commute E1 past E12^e... wait, E1 is already to the left in PBW order.
    So E1 E12^e is in PBW form. Good.
    E1^c E1 = E1^{c+1}. Good.

    So (E1^c E12^e E2^d) * E1:
    - First, E2^d E1 = ? (need to commute E2 past E1, from the right).
      E2 E1 = q^{-1} E1 E2 - q^{-1} E12, so (X) E2 E1 = X (q^{-1} E1 E2 - q^{-1} E12).
      But we have E2^d E1, not (something) E2 E1.
      E2^d E1 = E2^{d-1} (E2 E1) = E2^{d-1} (q^{-1} E1 E2 - q^{-1} E12)
              = q^{-1} E2^{d-1} E1 E2 - q^{-1} E2^{d-1} E12.
      Now E2^{d-1} E1: recurse. And E2^{d-1} E12 = q^{d-1} E12 E2^{d-1} (from E2 E12 = q E12 E2).
      But we want E2^{d-1} E12 in a form where E12 is to the LEFT of E2^{d-1} (PBW).
      E2 E12 = q E12 E2 => E2^{d-1} E12 = q^{d-1} E12 E2^{d-1}.
      So E2^d E1 = q^{-1} (E2^{d-1} E1) E2 - q^{-1} q^{d-1} E12 E2^{d-1}.
      This recursion terminates at d=0: E2^0 E1 = E1.
    This is getting complex. Let me just implement it recursively.
    """
    new = {}
    for (c, e, d), v in elem.items():
        if d > 0:
            # E2^d E1 = q^{-1} (E2^{d-1} E1) E2 - q^{d-2} E12 E2^{d-1}
            # We need (E1^c E12^e E2^d) E1 = E1^c E12^e (E2^d E1)
            # = E1^c E12^e [q^{-1} (E2^{d-1} E1) E2 - q^{d-2} E12 E2^{d-1}]
            # = q^{-1} E1^c E12^e (E2^{d-1} E1) E2 - q^{d-2} E1^c E12^{e+1} E2^{d-1}
            # The first term still has (E2^{d-1} E1) which needs further reduction.
            # This is a recursion on d.
            terms = _e2power_e1(d)  # E2^d E1 in PBW form {(c', e', d'): coeff}
            for (cp, ep, dp), vp in terms.items():
                # (E1^c E12^e) * (E1^{cp} E12^{ep} E2^{dp})
                # E12^e E1^{cp}: E12 E1 = q E1 E12, so E12^e E1^{cp} = q^{e*cp} E1^{cp} E12^e.
                # Then E1^c E1^{cp} = E1^{c+cp}. E12^e E12^{ep} = E12^{e+ep}.
                # E2^dp stays. So result: q^{e*cp} E1^{c+cp} E12^{e+ep} E2^{dp}.
                if c + cp < ELL and e + ep < ELL:
                    phase = Q ** (e * cp)
                    key = (c + cp, e + ep, dp)
                    new[key] = new.get(key, 0) + v * vp * phase
        else:
            # d == 0: (E1^c E12^e) E1 = E1^c (E12^e E1) = E1^c (q^e E1 E12^e) = q^e E1^{c+1} E12^e
            if c + 1 < ELL:
                phase = Q ** e
                key = (c + 1, e, 0)
                new[key] = new.get(key, 0) + v * phase
    return {k: v for k, v in new.items() if abs(v) > 1e-13}


def _e2power_e1(d):
    """Compute E2^d * E1 in PBW form {(c, e, d'): coeff}.
    E2^0 E1 = E1 = {(1, 0, 0): 1.0}.
    E2^1 E1 = q^{-1} E1 E2 - q^{-1} E12 = {(1, 0, 1): q^{-1}, (0, 1, 0): -q^{-1}}.
    E2^d E1 = q^{-1} (E2^{d-1} E1) E2 - q^{d-2} E12 E2^{d-1}.
    """
    if d == 0:
        return {(1, 0, 0): 1.0}
    prev = _e2power_e1(d - 1)
    result = {}
    # Term 1: q^{-1} * (E2^{d-1} E1) * E2 — just increment d' by 1
    for (cp, ep, dp), vp in prev.items():
        if dp + 1 < ELL:
            key = (cp, ep, dp + 1)
            result[key] = result.get(key, 0) + vp * Q_INV
    # Term 2: -q^{d-2} E12 E2^{d-1} = -q^{d-2} E1^0 E12^1 E2^{d-1}
    if d - 1 < ELL:
        key = (0, 1, d - 1)
        phase = -Q ** (d - 2)
        result[key] = result.get(key, 0) + phase
    return {k: v for k, v in result.items() if abs(v) > 1e-13}


def e_mult_by_E12_right(elem):
    """(E1^c E12^e E2^d) * E12.
    E2^d E12 = q^d E12 E2^d (PBW form, since E12 before E2). Wait, that's already PBW.
    Actually E2^d E12 = q^d E12 E2^d. So (E1^c E12^e E2^d) E12 = E1^c E12^e (E2^d E12)
    = E1^c E12^e (q^d E12 E2^d) = q^d E1^c E12^{e+1} E2^d. Vanishes if e+1 == ell.
    """
    new = {}
    for (c, e, d), v in elem.items():
        if e + 1 < ELL:
            phase = Q ** d  # E2^d E12 = q^d E12 E2^d
            key = (c, e + 1, d)
            new[key] = new.get(key, 0) + v * phase
    return {k: v for k, v in new.items() if abs(v) > 1e-13}


def e_mult_by_E2_right(elem):
    """(E1^c E12^e E2^d) * E2 = E1^c E12^e E2^{d+1}. Vanishes if d+1 == ell.
    E2 commutes with itself, and it's the last in PBW order, so just increment d.
    """
    new = {}
    for (c, e, d), v in elem.items():
        if d + 1 < ELL:
            key = (c, e, d + 1)
            new[key] = new.get(key, 0) + v
    return {k: v for k, v in new.items() if abs(v) > 1e-13}


def multiply_monomials(a1, b1, c1, e1, d1, a2, b2, c2, e2, d2):
    """Multiply (K1^a1 K2^b1 E1^c1 E12^e1 E2^d1) * (K1^a2 K2^b2 E1^c2 E12^e2 E2^d2).

    To move K1^a2 (from the right factor) to the left past E1^c1 E12^e1 E2^d1 (from the left factor):
    We use K1 E1 = q^2 E1 K1, i.e., K1 E1 K1^{-1} = q^2 E1.
    So E1 K1 = q^{-2} K1 E1 (move K1 to the left of E1, picking up q^{-2}).
    More generally: E1^c1 K1^a2 = q^{-2 a2 c1} K1^a2 E1^c1.
    Similarly E12^e1 K1^a2 = q^{-a2 e1} K1^a2 E12^e1 (since K1 E12 K1^{-1} = q E12 => E12 K1 = q^{-1} K1 E12).
    And E2^d1 K1^a2 = q^{a2 d1} K1^a2 E2^d1 (since K1 E2 K1^{-1} = q^{-1} E2 => E2 K1 = q K1 E2).
    Same for K2: E1^c1 K2^b2 = q^{b2 c1} K2^b2 E1^c1 (since K2 E1 K2^{-1} = q^{-1} E1 => E1 K2 = q K2 E1).
    E12^e1 K2^b2 = q^{-b2 e1} K2^b2 E12^e1.
    E2^d1 K2^b2 = q^{-2 b2 d1} K2^b2 E2^d1.
    """
    # Phase from moving K1^a2 K2^b2 to the left past E1^c1 E12^e1 E2^d1
    phase_k = (Q ** (-2*a2*c1 - a2*e1 + a2*d1)) * (Q ** (b2*c1 - b2*e1 - 2*b2*d1))
    a_sum = (a1 + a2) % ELL
    b_sum = (b1 + b2) % ELL

    # Multiply the E-parts
    left_e = {(c1, e1, d1): 1.0}
    right_e = {(c2, e2, d2): 1.0}
    e_prod = e_multiply(left_e, right_e)

    # Combine
    result = {}
    for (c, e, d), v in e_prod.items():
        key = (a_sum, b_sum, c, e, d)
        result[key] = result.get(key, 0) + v * phase_k
    return {k: v for k, v in result.items() if abs(v) > 1e-13}


def build_mult_sparse(dim):
    """Build sparse multiplication table: ms[i][j] = [(l, mult[l,i,j]), ...]."""
    ms = [[[] for _ in range(dim)] for _ in range(dim)]
    for i in range(dim):
        a1, b1, c1, e1, d1 = from_idx(i)
        for j in range(dim):
            a2, b2, c2, e2, d2 = from_idx(j)
            prod = multiply_monomials(a1, b1, c1, e1, d1, a2, b2, c2, e2, d2)
            for (a, b, c, e, d), v in prod.items():
                l = idx(a, b, c, e, d)
                ms[i][j].append((l, v))
    return ms


def sanity_checks(ms, dim):
    """Verify algebra relations."""
    print("Sanity checks:")
    e0 = idx(0, 0, 0, 0, 0)  # identity
    K1 = idx(1, 0, 0, 0, 0)
    K2 = idx(0, 1, 0, 0, 0)
    E1 = idx(0, 0, 1, 0, 0)
    E2 = idx(0, 0, 0, 0, 1)
    E12 = idx(0, 0, 0, 1, 0)

    # 1 * x = x * 1 = x
    ok = True
    for i in range(dim):
        if abs(ms[i][e0][0][1] - 1.0) > 1e-12 if ms[i][e0] else False:
            ok = False; break
        if abs(ms[i][e0] and ms[i][e0][0][0] - i) > 1e-12 if ms[i][e0] else False:
            ok = False; break
    print(f"  1 * x = x: {ok}")

    # K1^3 = 1
    K1_2 = idx(2, 0, 0, 0, 0)
    prod = ms[K1][K1]
    k1sq = None
    for (l, v) in prod:
        if abs(v - 1.0) < 1e-12:
            k1sq = l
    # K1 * K1^2 should give 1
    prod = ms[K1][k1sq] if k1sq is not None else []
    is_one = any(l == e0 and abs(v - 1.0) < 1e-12 for (l, v) in prod)
    print(f"  K1^3 = 1: {is_one}")

    # E1^3 = 0
    E1_2 = idx(0, 0, 2, 0, 0)
    prod = ms[E1_2][E1]
    is_zero = len(prod) == 0
    print(f"  E1^3 = 0: {is_zero}")

    # E2^3 = 0
    E2_2 = idx(0, 0, 0, 0, 2)
    prod = ms[E2_2][E2]
    is_zero = len(prod) == 0
    print(f"  E2^3 = 0: {is_zero}")

    # E12^3 = 0
    E12_2 = idx(0, 0, 0, 2, 0)
    prod = ms[E12_2][E12]
    is_zero = len(prod) == 0
    print(f"  E12^3 = 0: {is_zero}")

    # K1 E1 = q^2 E1 K1
    prod = ms[K1][E1]  # K1 * E1
    k1e1 = None
    for (l, v) in prod:
        k1e1 = (l, v)
    prod = ms[E1][K1]  # E1 * K1
    e1k1 = None
    for (l, v) in prod:
        e1k1 = (l, v)
    if k1e1 and e1k1:
        # K1 E1 should be q^2 * (E1 K1 normal form) = q^2 * (K1 E1 normal form)? Let me think.
        # K1 E1 in PBW form: K1^1 E1^1 = idx(1,0,1,0,0).
        # E1 K1 = q^{-2} K1 E1 (since K1 E1 K1^{-1} = q^2 E1 => K1 E1 = q^2 E1 K1 => E1 K1 = q^{-2} K1 E1).
        # So ms[K1][E1] should be [(idx(1,0,1,0,0), 1.0)] and ms[E1][K1] should be [(idx(1,0,1,0,0), q^{-2})].
        ok = (k1e1[0] == idx(1,0,1,0,0) and abs(k1e1[1] - 1.0) < 1e-12 and
              e1k1[0] == idx(1,0,1,0,0) and abs(e1k1[1] - Q_INV**2) < 1e-12)
        print(f"  K1 E1 = q^2 E1 K1: {ok} (K1*E1={k1e1}, E1*K1={e1k1})")
    else:
        print(f"  K1 E1 check failed: K1*E1={k1e1}, E1*K1={e1k1}")

    # E1 E2 - q E2 E1 = E12
    prod_e1e2 = ms[E1][E2]
    prod_e2e1 = ms[E2][E1]
    # E1 E2 - q E2 E1 should equal E12 (i.e., idx(0,0,0,1,0))
    diff = {}
    for (l, v) in prod_e1e2:
        diff[l] = diff.get(l, 0) + v
    for (l, v) in prod_e2e1:
        diff[l] = diff.get(l, 0) - v * Q
    # Should be {E12_idx: 1.0}
    e12_idx = idx(0, 0, 0, 1, 0)
    ok = (len(diff) == 1 and e12_idx in diff and abs(diff[e12_idx] - 1.0) < 1e-12)
    print(f"  E1 E2 - q E2 E1 = E12: {ok} (diff = {diff})")

    # Quantum Serre: E1^2 E2 + E1 E2 E1 + E2 E1^2 = 0 (for q + q^{-1} = -1)
    E1_2_idx = idx(0, 0, 2, 0, 0)
    # E1^2 E2 = ms[E1_2][E2] then it's a vector. We need to compute (E1^2 * E2 + E1 * E2 * E1 + E2 * E1^2) = 0.
    # This requires multiplying three elements. Let me compute it as:
    # (E1^2 * E2) + (E1 * (E2 * E1)) + (E2 * E1^2)
    # First compute E2 * E1 = ms[E2][E1]
    e2_e1 = ms[E2][E1]
    # Then E1 * (E2 E1): for each (l, v) in e2_e1, multiply E1 * basis[l] and sum
    e1_e2_e1 = {}
    for (l, v) in e2_e1:
        for (l2, v2) in ms[E1][l]:
            e1_e2_e1[l2] = e1_e2_e1.get(l2, 0) + v * v2
    # E1^2 E2 = E1 * (E1 * E2)
    e1_e2 = ms[E1][E2]
    e1sq_e2 = {}
    for (l, v) in e1_e2:
        for (l2, v2) in ms[E1][l]:
            e1sq_e2[l2] = e1sq_e2.get(l2, 0) + v * v2
    # E2 * E1^2
    e1sq_idx = idx(0, 0, 2, 0, 0)
    e2_e1sq = ms[E2][e1sq_idx]
    # Sum
    total = {}
    for (l, v) in e1sq_e2.items():
        total[l] = total.get(l, 0) + v
    for (l, v) in e1_e2_e1.items():
        total[l] = total.get(l, 0) + v
    for (l, v) in e2_e1sq:
        total[l] = total.get(l, 0) + v
    total = {k: v for k, v in total.items() if abs(v) > 1e-10}
    print(f"  Serre I (E1^2 E2 + E1 E2 E1 + E2 E1^2 = 0): {len(total) == 0} (residual: {total})")


def compute_hh2():
    dim = DIM
    print(f"\n=== HH^2(B+(u_q(sl_3)), C) at ell = {ELL} ===")
    print(f"dim B+ = {dim}")
    t0 = time.time()
    ms = build_mult_sparse(dim)
    print(f"Mult table: {time.time()-t0:.1f}s")
    sanity_checks(ms, dim)

    # Counit: eps(K1^a K2^b E1^c E12^e E2^d) = 1 if c=e=d=0, else 0
    epsilon = np.zeros(dim, dtype=complex)
    for a in range(ELL):
        for b in range(ELL):
            epsilon[idx(a, b, 0, 0, 0)] = 1.0

    # 2D weights
    wts = [weight(i) for i in range(dim)]
    unique_wts = sorted(set(wts))
    print(f"Unique weights: {len(unique_wts)}")

    # Build d^1 by weight
    print("Building d^1 by weight...")
    t0 = time.time()
    wt_indices = {w: [i for i in range(dim) if wts[i] == w] for w in unique_wts}
    # C^2 pairs by total weight
    c2_by_wt = {w: [] for w in unique_wts}
    for i in range(dim):
        for j in range(dim):
            w = (wts[i][0] + wts[j][0]) % ELL, (wts[i][1] + wts[j][1]) % ELL
            c2_by_wt[w].append(i * dim + j)
    c2_maps = {w: {ij: k for k, ij in enumerate(pairs)} for w, pairs in c2_by_wt.items()}

    d1_blocks = {}
    total_rank_d1 = 0
    for w in unique_wts:
        cols = wt_indices[w]
        rows = c2_by_wt[w]
        n_cols, n_rows = len(cols), len(rows)
        if n_cols == 0 or n_rows == 0:
            d1_blocks[w] = None; continue
        d1 = np.zeros((n_rows, n_cols), dtype=complex)
        for col, i_f in enumerate(cols):
            for row, ij in enumerate(rows):
                i, j = ij // dim, ij % dim
                mult_if = sum(v for (l, v) in ms[i][j] if l == i_f)
                d1[row, col] = (epsilon[i]*(1.0 if j==i_f else 0.0) - mult_if
                               + (1.0 if i==i_f else 0.0)*epsilon[j])
        d1_blocks[w] = d1
        s = np.linalg.svd(d1, compute_uv=False)
        tol = max(d1.shape) * (s[0] if len(s)>0 else 0) * 1e-14
        rank = int(np.sum(s > tol)) if len(s) > 0 else 0
        total_rank_d1 += rank
    print(f"  d^1: {time.time()-t0:.1f}s, total rank = {total_rank_d1}")

    # Build d^2 by weight
    print("Building d^2 by weight...")
    t0 = time.time()
    total_rank_d2 = 0
    total_dim_ker_d2 = 0
    hh2_total = 0
    for w in unique_wts:
        # C^3 triples with total weight w
        triples = []
        for i in range(dim):
            for j in range(dim):
                k_wt = ((w[0] - wts[i][0] - wts[j][0]) % ELL, (w[1] - wts[i][1] - wts[j][1]) % ELL)
                for k in wt_indices.get(k_wt, []):
                    triples.append((i, j, k))
        n_rows = len(triples)
        n_cols = len(c2_by_wt[w])
        if n_rows == 0 or n_cols == 0:
            continue
        cmap = c2_maps[w]
        rows_l, cols_l, vals_l = [], [], []
        for row, (i, j, k) in enumerate(triples):
            ei = epsilon[i]
            if abs(ei) > 1e-13:
                jk = j*dim+k
                if jk in cmap:
                    rows_l.append(row); cols_l.append(cmap[jk]); vals_l.append(ei)
            for (l, v) in ms[i][j]:
                lk = l*dim+k
                if lk in cmap:
                    rows_l.append(row); cols_l.append(cmap[lk]); vals_l.append(-v)
            for (l, v) in ms[j][k]:
                il = i*dim+l
                if il in cmap:
                    rows_l.append(row); cols_l.append(cmap[il]); vals_l.append(v)
            ek = epsilon[k]
            if abs(ek) > 1e-13:
                ij = i*dim+j
                if ij in cmap:
                    rows_l.append(row); cols_l.append(cmap[ij]); vals_l.append(-ek)
        d2 = sparse.csr_matrix((vals_l, (rows_l, cols_l)), shape=(n_rows, n_cols), dtype=complex)
        gram = (d2.conj().T @ d2).toarray()
        eigvals = np.sort(np.abs(np.linalg.eigvalsh(gram)))[::-1]
        if len(eigvals) == 0 or eigvals[0] == 0:
            rank = 0
        else:
            tol = max(d2.shape) * eigvals[0] * 1e-10
            rank = int(np.sum(eigvals > tol))
        dim_ker = n_cols - rank
        s1 = np.linalg.svd(d1_blocks[w], compute_uv=False) if d1_blocks[w] is not None else np.array([])
        tol1 = max(d1_blocks[w].shape)*(s1[0] if len(s1)>0 else 0)*1e-14 if d1_blocks[w] is not None else 0
        rank1 = int(np.sum(s1 > tol1)) if len(s1) > 0 else 0
        hh2_w = dim_ker - rank1
        total_rank_d2 += rank
        total_dim_ker_d2 += dim_ker
        hh2_total += hh2_w
        print(f"  wt {w}: C²={n_cols} C³={n_rows} rank(d²)={rank} ker(d²)={dim_ker} rank(d¹)={rank1} HH²={hh2_w}  [{time.time()-t0:.1f}s]")

    print(f"\nTOTAL: dim HH² = {hh2_total}")
    print(f"Predicted = 6 (binom(3,2) + |Phi^+| = 3 + 3)")
    print(f"MATCH: {hh2_total == 6}")
    return hh2_total


if __name__ == "__main__":
    compute_hh2()
