#!/usr/bin/env python3
"""
Compute HH^2(B+(u_q(sl_2)), C) at ell = 3.

B+(sl_2) is generated by K, E (with K^3=1, E^3=0, KE = q^2 EK).
Basis: {K^a E^b : 0 <= a,b < 3}, dimension 9.

This is a quick computation to test the conjecture:
  dim HH^2(B+(sl_n), C) = n + |Phi^+|
For sl_2: n=1, |Phi^+|=1, so predicted dim = 2.
"""
import cmath, math, time
import numpy as np
from scipy import sparse

ELL = 3
Q = cmath.exp(2j * math.pi / ELL)
Q_INV = Q ** (-1)
D = Q - Q_INV
DIM = ELL * ELL  # 9


def idx(a, b):
    return a * ELL + b


def from_idx(i):
    return i // ELL, i % ELL


def weight(i):
    """E-weight of K^a E^b is 2b mod ell."""
    a, b = from_idx(i)
    return (2 * b) % ELL


def multiply_monomials(a1, b1, a2, b2):
    """(K^a1 E^b1) * (K^a2 E^b2).
    E^b1 K^a2 = q^{-2 a2 b1} K^a2 E^b1 (from KE = q^2 EK => EK = q^{-2} KE).
    So (K^a1 E^b1)(K^a2 E^b2) = q^{-2 a2 b1} K^{a1+a2} E^{b1+b2}.
    """
    phase = Q ** (-2 * a2 * b1)
    a = (a1 + a2) % ELL
    b = b1 + b2
    if b >= ELL:
        return {}  # E^ell = 0
    return {(a, b): phase}


def build_mult():
    mult = np.zeros((DIM, DIM, DIM), dtype=complex)
    for i in range(DIM):
        a1, b1 = from_idx(i)
        for j in range(DIM):
            a2, b2 = from_idx(j)
            prod = multiply_monomials(a1, b1, a2, b2)
            for (a, b), v in prod.items():
                mult[idx(a, b), i, j] = v
    return mult


def compute_hh2():
    print(f"\n=== HH^2(B+(u_q(sl_2)), C) at ell = {ELL} ===")
    print(f"dim B+ = {DIM}")
    mult = build_mult()
    print(f"Mult table nnz: {int(np.sum(np.abs(mult) > 1e-13))}")

    # Counit: eps(K^a E^b) = 1 if b=0, else 0
    epsilon = np.zeros(DIM, dtype=complex)
    for a in range(ELL):
        epsilon[idx(a, 0)] = 1.0

    wts = np.array([weight(i) for i in range(DIM)])

    # Build d^1 and d^2 by weight
    total_rank_d1 = 0
    total_dim_ker_d2 = 0
    hh2_total = 0

    for c in range(ELL):
        wt_idx_c = [i for i in range(DIM) if wts[i] == c]
        c2_pairs = [i*DIM+j for i in range(DIM) for j in range(DIM) if (wts[i]+wts[j])%ELL == c]
        c2_map = {ij: k for k, ij in enumerate(c2_pairs)}

        n_c1 = len(wt_idx_c)
        n_c2 = len(c2_pairs)
        if n_c1 == 0 or n_c2 == 0:
            continue

        # d^1
        d1 = np.zeros((n_c2, n_c1), dtype=complex)
        for col, i_f in enumerate(wt_idx_c):
            for row, ij in enumerate(c2_pairs):
                i, j = ij // DIM, ij % DIM
                d1[row, col] = (epsilon[i]*(1.0 if j==i_f else 0.0)
                               - mult[i_f, i, j]
                               + (1.0 if i==i_f else 0.0)*epsilon[j])
        s1 = np.linalg.svd(d1, compute_uv=False)
        tol1 = max(d1.shape)*(s1[0] if len(s1)>0 else 0)*1e-14
        rank1 = int(np.sum(s1 > tol1)) if len(s1) > 0 else 0

        # d^2
        triples = []
        for i in range(DIM):
            for j in range(DIM):
                k_wt = (c - wts[i] - wts[j]) % ELL
                for k in range(DIM):
                    if wts[k] == k_wt:
                        triples.append((i, j, k))
        n_c3 = len(triples)

        rows_l, cols_l, vals_l = [], [], []
        for row, (i, j, k) in enumerate(triples):
            ei = epsilon[i]
            if abs(ei) > 1e-13:
                jk = j*DIM+k
                if jk in c2_map:
                    rows_l.append(row); cols_l.append(c2_map[jk]); vals_l.append(ei)
            for l in range(DIM):
                v = mult[l, i, j]
                if abs(v) > 1e-13:
                    lk = l*DIM+k
                    if lk in c2_map:
                        rows_l.append(row); cols_l.append(c2_map[lk]); vals_l.append(-v)
            for l in range(DIM):
                v = mult[l, j, k]
                if abs(v) > 1e-13:
                    il = i*DIM+l
                    if il in c2_map:
                        rows_l.append(row); cols_l.append(c2_map[il]); vals_l.append(v)
            ek = epsilon[k]
            if abs(ek) > 1e-13:
                ij = i*DIM+j
                if ij in c2_map:
                    rows_l.append(row); cols_l.append(c2_map[ij]); vals_l.append(-ek)

        d2 = sparse.csr_matrix((vals_l, (rows_l, cols_l)), shape=(n_c3, n_c2), dtype=complex)
        gram = (d2.conj().T @ d2).toarray()
        eigvals = np.sort(np.abs(np.linalg.eigvalsh(gram)))[::-1]
        if len(eigvals) == 0 or eigvals[0] == 0:
            rank2 = 0
        else:
            tol2 = max(d2.shape) * eigvals[0] * 1e-10
            rank2 = int(np.sum(eigvals > tol2))
        dim_ker = n_c2 - rank2
        hh2_c = dim_ker - rank1

        total_rank_d1 += rank1
        total_dim_ker_d2 += dim_ker
        hh2_total += hh2_c
        print(f"  wt {c}: C²={n_c2} C³={n_c3} rank(d²)={rank2} ker(d²)={dim_ker} rank(d¹)={rank1} HH²={hh2_c}")

    print(f"\nTOTAL: dim HH²(B+(sl_2), C) = {hh2_total}")
    print(f"Old conjecture (binom(n+1,2) + |Phi^+|): {1 + 1} = 2")
    print(f"New conjecture (n + |Phi^+|): {1 + 1} = 2")
    print(f"MATCH: {hh2_total == 2}")
    return hh2_total


if __name__ == "__main__":
    compute_hh2()
